[package]
name = "cnvs-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cnvs-protocol = { path = "../cnvs-protocol" }
dirs = "6"
futures-util = "0.3"
serde_json = "1"
tokio = { version = "1", features = ["io-util", "macros", "net", "time"] }
tokio-tungstenite = "0.27"
url = "2"


[lints.clippy]
# Start with standard pedantic rules
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

# Deny explicit footguns in core logic
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
indexing_slicing = "deny" # Forces safe checking (.get())
print_stdout = "deny" # Forces tracing/logging abstractions
print_stderr = "deny"
